Try

diff --git a/.github/workflows/feature-azuredeployment_thesis-client.yml b/.github/workflows/feature-azuredeployment_thesis-client.yml
--- a/.github/workflows/feature-azuredeployment_thesis-client.yml
+++ b/.github/workflows/feature-azuredeployment_thesis-client.yml
@@ -30,6 +30,15 @@ jobs:
           npm install
           npm run build
 
+      - name: Check if publish profile secret is loaded
+        run: |
+              if [ -z "${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_60FD089D48634BADB64534E506D31CD2 }}" ]; then
+                echo "❌ Secret AZURE_WEBAPP_PUBLISH_PROFILE is missing or empty."
+                exit 1
+              else
+                echo "✅ Secret AZURE_WEBAPP_PUBLISH_PROFILE is set."
+              fi
+
       - name: Deploy to Azure Web App
         uses: azure/webapps-deploy@v3
         with:
@@ -37,11 +46,4 @@ jobs:
           slot-name: 'Production'
           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_60FD089D48634BADB64534E506D31CD2 }}
           package: ./client
-      - name: Check if publish profile secret is loaded
-        run: |
-            if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" ]; then
-              echo "❌ Secret AZURE_WEBAPP_PUBLISH_PROFILE is missing or empty."
-              exit 1
-            else
-              echo "✅ Secret AZURE_WEBAPP_PUBLISH_PROFILE is set."
-            fi
+      
